package model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.Date;

/**
 * Created by Daniel on 02.01.2017.
 */

@DynamoDBTable(tableName = "openingDates")
public class OpeningDate {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String tavernName;
    @DynamoDBAttribute
    private Date startDate;
    @DynamoDBAttribute
    private Date endDate;


    public OpeningDate(String tavernName, Date startDate, Date endDate) {
        this.tavernName = tavernName;
        this.startDate = startDate;
        this.endDate = endDate;
    }


    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTavernName() {
        return tavernName;
    }

    public void setTavernName(String tavernName) {
        this.tavernName = tavernName;
    }

}
