package model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.Date;

/**
 * Created by Daniel on 02.01.2017.
 */

@DynamoDBTable(tableName = "reviews")
public class Review {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String tavernName;
    @DynamoDBAttribute
    private double rating;
    @DynamoDBAttribute
    private String message;
    @DynamoDBAttribute
    private Date date;
    @DynamoDBAttribute
    private String userID;
    @DynamoDBAttribute
    private String userName;


    public Review(String tavernName, String userID, String userName, String message, double rating, Date date) {
        this.tavernName = tavernName;
        this.userID = userID;
        this.userName = userName;
        this.message = message;
        this.rating = rating;
        this.date = date;
    }

    public Review() {
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public double getRating() {
        return rating;
    }

    public void setRating(double rating) {
        this.rating = rating;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getTavernName() {
        return tavernName;
    }

    public void setTavernName(String tavernName) {
        this.tavernName = tavernName;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

}
